/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Blog_bottom: typeof import('./src/components/blog_bottom/index.vue')['default']
    Blog_top: typeof import('./src/components/blog_top/index.vue')['default']
    Bottom: typeof import('./src/components/bottom/index.vue')['default']
    ElButtion: typeof import('element-plus/es')['ElButtion']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/Test.vue')['default']
    Topbar: typeof import('./src/components/topBar/index.vue')['default']
    TopBar: typeof import('./src/components/topBar/index.vue')['default']
  }
}
