name: "athena"
mode: "dev"
port: 3939
version: "v1"

# 日志配置
log:
  level: "debug"
  filename: "./logs/athena.log"
  max_size: 200
  max_age: 30
  max_backups: 7

# mysql配置
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root"
  dbname: "athena"
  max_open_conns: 200
  max_idle_conns: 50

# redis配置
redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  pool_size: 100

# 雪花算法配置
snowflake:
  start_time: "2024-01-01"
  machine_id: 39


